include(joinpath(@__DIR__,"../../scripts/lib/SolverPilotControl.jl"))
include(joinpath(@__DIR__,"../src/SolverPilot.jl"))
length(ARGS)==4 || error("usage: run_solver_pilot.jl CONTROL STAGE SCRATCH COMPACT")
SolverPilotControl.validate(ARGS[1];live=true)
deadline=parse(Float64,get(ENV,"PROJECT_B_PILOT_DEADLINE","0"))
deadline>time() || error("missing or expired pilot allocation deadline")
SolverPilot.run_stage(ARGS...;deadline,stop_file=get(ENV,"PROJECT_B_PRETIMEOUT_REQUEST_FILE",""))
